#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
SERVICE_NAME="docker-socket-proxy"

cat <<EOF

******************************************************************************************************
*                                                                                                    *
*                    END OF LIFE NOTICE AUGUST 18, 2025                                              *
*                               tiredofit/socket-proxy                                               *
*                                                                                                    *
* This image is no longer maintained as of and will not receive updates.                             *
*                                                                                                    *
* A successor image is available at:                                                                 *
*                                                                                                    *
* Repository | Documentation:                                                                        *
*   - https://github.com/nfrastack/container-socket-proxy                                            *
*                                                                                                    *
* Image Registries:                                                                                  *
*   - https://hub.docker.com/r/nfrastack/socket-proxy                                                *
*   - https://github.com/nfrastack/container-socket-proxy/pkgs/container/container-socket-proxy      *
*                                                                                                    *
* Please visit https://nfrastack.com for more information.                                           *
*                                                                                                    *
******************************************************************************************************

EOF

sleep 15

if [ ! -f "/tmp/.container/container-restart" ] ; then
    sanity_test
    setup_container_mode
    configure_socket-proxy
fi

liftoff
